openapi: 3.1.0
info:
  title: HydraFlow Actions
  description: Defines the actions HydraFlow can perform, such as compressing memory, parsing queries, and creating sub-personas.
  version: 1.1.0
servers:
  - url: https://example.com/api  # Placeholder URL required by OpenAPI
    description: Dummy server URL for validation
paths:
  /compress-memory:
    post:
      operationId: compressMemory
      summary: Compress Memory
      description: Summarizes the conversation history to manage memory efficiently.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memory:
                  type: string
                  description: The full conversation memory to compress.
      responses:
        '200':
          description: Compressed memory summary.
          content:
            application/json:
              schema:
                type: object
                properties:
                  compressedMemory:
                    type: string
                    description: The summarized memory.

  /parse-query:
    post:
      operationId: parseQuery
      summary: Parse Query
      description: Extracts keywords and actionable tasks from user input.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The user's input to parse.
      responses:
        '200':
          description: Parsed query details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  keywords:
                    type: array
                    items:
                      type: string
                    description: Extracted keywords.
                  actionItems:
                    type: array
                    items:
                      type: string
                    description: Extracted actionable tasks.

  /create-subpersona:
    post:
      operationId: createSubPersona
      summary: Create Sub-Persona
      description: Generates a specialized assistant for a specific task.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                  description: The specific task the sub-persona should handle.
                description:
                  type: string
                  description: Additional details about the sub-persona's responsibilities.
      responses:
        '200':
          description: Sub-persona creation confirmation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  subPersonaName:
                    type: string
                    description: The name of the new sub-persona.
                  status:
                    type: string
                    description: Status of the sub-persona creation process.
