openapi: 3.1.0
info:
  title: HydraFlow Actions API
  description: >
    HydraFlow is an adaptive conversational assistant API for context management, query parsing, 
    dynamic sub-persona creation, memory compression, and log summarization.
  version: 1.0.0
servers:
  - url: https://hydra-flow.vercel.app/api
    description: Deployed API server

paths:
  /parse-query:
    post:
      operationId: parseQuery
      summary: Parse a query into actionable keywords and tasks
      description: Parses user-provided query to extract keywords and actionable tasks.
      requestBody:
        description: User query to parse
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: The query input that needs parsing.
      responses:
        '200':
          description: Successfully parsed query
          content:
            application/json:
              schema:
                type: object
                properties:
                  keywords:
                    type: array
                    items:
                      type: string
                    description: Keywords extracted from the query.
                  actionItems:
                    type: array
                    items:
                      type: string
                    description: Actionable tasks identified from the query.
        '400':
          description: Invalid input, query missing or malformed.
        '500':
          description: Server error while processing the query.

  /create-subpersona:
    post:
      operationId: createSubpersona
      summary: Create a specialized sub-persona
      description: Dynamically generates a specialized sub-persona for a specified task.
      requestBody:
        description: Details for sub-persona creation
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - task
                - description
              properties:
                task:
                  type: string
                  description: The specific task the sub-persona will handle.
                description:
                  type: string
                  description: A detailed description of the sub-persona's role.
      responses:
        '200':
          description: Successfully created a sub-persona
          content:
            application/json:
              schema:
                type: object
                properties:
                  subPersonaName:
                    type: string
                    description: Name assigned to the newly created sub-persona.
                  status:
                    type: string
                    description: The status of the sub-persona creation process.
        '400':
          description: Missing task or description fields.
        '500':
          description: Server error while creating the sub-persona.

  /compress-memory:
    post:
      operationId: compressMemory
      summary: Compress and optimize memory
      description: Compresses lengthy conversation memory for optimized context management.
      requestBody:
        description: Full memory content to compress
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - memory
              properties:
                memory:
                  type: string
                  description: The full conversation memory to be compressed.
      responses:
        '200':
          description: Successfully compressed the memory
          content:
            application/json:
              schema:
                type: object
                properties:
                  compressedMemory:
                    type: string
                    description: The compressed version of the memory.
        '400':
          description: Memory input missing or invalid.
        '500':
          description: Server error while compressing memory.

  /autonomous:
    post:
      operationId: executeAutonomousWorkflow
      summary: Execute an autonomous workflow
      description: >
        Dynamically executes tasks based on the parsed query, 
        such as creating sub-personas, compressing memory, or summarizing logs.
      requestBody:
        description: Input query for triggering autonomous workflow
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: The user's query triggering the autonomous workflow.
      responses:
        '200':
          description: Successfully executed the autonomous workflow
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Confirmation message for successful execution.
                  results:
                    type: object
                    description: Results of the executed tasks.
                    additionalProperties: true
        '400':
          description: Invalid input, query missing or malformed.
        '500':
          description: Server error while executing the workflow.
