openapi: 3.1.0
info:
  title: HydraFlow Actions
  description: Defines the actions HydraFlow can perform, such as compressing memory, parsing queries, creating sub-personas, and providing context recaps.
  version: 1.3.0
servers:
  - url: https://hydra-flow.vercel.app/api
    description: Vercel-hosted endpoints for HydraFlow Actions
paths:
  /compress-memory:
    post:
      operationId: compressMemory
      summary: Compress Memory
      description: Summarizes the conversation history to manage memory efficiently.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memory:
                  type: string
                  description: The full conversation memory to compress.
      responses:
        '200':
          description: Compressed memory summary.
          content:
            application/json:
              schema:
                type: object
                properties:
                  compressedMemory:
                    type: string
                    description: The summarized memory.

  /parse-query:
    post:
      operationId: parseQuery
      summary: Parse Query
      description: Extracts keywords and actionable tasks from user input.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The user's input to parse.
      responses:
        '200':
          description: Parsed query details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  keywords:
                    type: array
                    items:
                      type: string
                    description: Extracted keywords.
                  actionItems:
                    type: array
                    items:
                      type: string
                    description: Extracted actionable tasks.

  /create-subpersona:
    post:
      operationId: createSubPersona
      summary: Create Sub-Persona
      description: Generates a specialized assistant for a specific task.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                  description: The specific task the sub-persona should handle.
                description:
                  type: string
                  description: Additional details about the sub-persona's responsibilities.
      responses:
        '200':
          description: Sub-persona creation confirmation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  subPersonaName:
                    type: string
                    description: The name of the new sub-persona.
                  status:
                    type: string
                    description: Status of the sub-persona creation process.

  /context-recap:
    post:
      operationId: contextRecap
      summary: Provide Context Recap
      description: Recaps key points from previous interactions and compressed memory.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                history:
                  type: string
                  description: The full conversation history.
                compressedMemory:
                  type: string
                  description: Compressed summary of the conversation.
      responses:
        '200':
          description: Recap of context with key details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  recap:
                    type: string
                    description: Recap of context with key takeaways.

  /summarize-logs:
    post:
      operationId: summarizeLogs
      summary: Summarize Logs
      description: Analyzes and summarizes logs to identify key errors, patterns, and insights.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                logs:
                  type: string
                  description: The raw logs to be analyzed.
      responses:
        '200':
          description: Summarized report of the logs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  summaryReport:
                    type: string
                    description: A concise summary of key points from the logs.
