openapi: 3.1.0
info:
  title: HydraFlow Actions API
  description: >
    HydraFlow is an adaptive conversational assistant API for context management, query parsing,
    dynamic sub-persona creation, memory compression, log summarization, and context recapping.
  version: 1.3.0
servers:
  - url: https://hydra-flow.vercel.app/api
    description: Deployed API server

components:
  schemas:
    ParseQueryResponse:
      type: object
      properties:
        keywords:
          type: array
          items:
            type: string
          description: Keywords extracted from the query.
        actionItems:
          type: array
          items:
            type: string
          description: Actionable tasks identified from the query.
        taskCard:
          type: object
          properties:
            id:
              type: string
              description: Unique ID for the task card.
            goal:
              type: string
              description: Goal of the task.
            priority:
              type: string
              description: Task priority (e.g., High, Medium).
            subtasks:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique ID for the subtask.
                  task:
                    type: string
                    description: Subtask description.
                  status:
                    type: string
                    description: Subtask status (e.g., pending, completed).
                  dependencies:
                    type: array
                    items:
                      type: string
                    description: Dependencies for this subtask.

    SubpersonaResponse:
      type: object
      properties:
        subPersonaName:
          type: string
          description: Name assigned to the newly created sub-persona.
        status:
          type: string
          description: Status of the sub-persona creation process.

    MemoryCompressionResponse:
      type: object
      properties:
        compressedMemory:
          type: string
          description: Compressed memory summary.

    LogSummary:
      type: object
      properties:
        totalEntries:
          type: integer
          description: Total number of log entries analyzed.
        errorCount:
          type: integer
          description: Number of error-like patterns detected.
        firstFiveLines:
          type: string
          description: The first five lines of the log for a quick overview.

    FeedbackEntry:
      type: object
      properties:
        responseId:
          type: string
          description: Response ID associated with the feedback.
        userFeedback:
          type: string
          description: Feedback text provided by the user.
        rating:
          type: integer
          minimum: 1
          maximum: 5
          description: Rating given by the user (1-5).
        timestamp:
          type: string
          format: date-time
          description: Time of feedback submission.

    FeedbackSummary:
      type: object
      properties:
        totalFeedback:
          type: integer
          description: Total number of feedback entries.
        averageRating:
          type: number
          format: float
          description: Average rating from all feedback entries.
        feedbackEntries:
          type: array
          items:
            $ref: '#/components/schemas/FeedbackEntry'

    ServerErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.

  responses:
    ServerError:
      description: Server error while processing the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerErrorResponse'

paths:
  /parse-query:
    post:
      summary: Parse a query into actionable keywords and tasks
      operationId: parseQuery
      description: Parses user-provided query to extract keywords and actionable tasks.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The query input that needs parsing.
      responses:
        '200':
          description: Successfully parsed query.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParseQueryResponse'
        '500':
          $ref: '#/components/responses/ServerError'

  /compress-memory:
    post:
      summary: Compress and optimize memory
      operationId: compressMemory
      description: Compresses lengthy conversation memory for optimized context management.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memory:
                  type: string
                  description: The full conversation memory to be compressed.
      responses:
        '200':
          description: Successfully compressed memory.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemoryCompressionResponse'
        '500':
          $ref: '#/components/responses/ServerError'

  /feedback/summary:
    get:
      summary: Retrieve feedback summary
      operationId: getFeedbackSummary
      description: Fetches a summarized view of all feedback, including totals and averages.
      responses:
        '200':
          description: Successfully retrieved feedback summary.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedbackSummary'
        '500':
          $ref: '#/components/responses/ServerError'
